### ISSUE TITLE
Inline HTML as value

### ISSUE THREAD

**Issue by niknetniko** [expandjs/mat-editor#2]
I was wondering if it would be possible to use the inline HTML as the value, for example:

``` html
<mat-editor line-numbers mode="javascript">
function coolFunction() {
    console.log("Woooah! Cool function");
}
</mat-editor>
```

Would something like this ever be possible?

**Comment by Pupix** [comment]
Hello!

At the moment this is not possible. We have tried this before with other elements (xp-markdown) and the browser renders the tags as normal (if you write HTML). To make this work you would need some `<script>` tags with unknown `type`s which is not really what a user would expect. If you have any suggestions on how to make it work seamlessly feel free to let us know.

Cheers!

**Comment by niknetniko** [comment]
Thank you for your response. I'll do some experimenting, and if I find something I'll let you know, who knows.
